### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by hughesjeff** [Purdue-ACM-SIGAPP/PurdueLaundry#10]
There are basically no comments anywhere to be seen.

**Comment by mhoc** [comment]
Comments are a really hard thing to get right. We're always taught that too many are better than too few, but writing too many might not only be a waste of time, but also has the effect of cluttering the code and making it harder to read.

One example, Kyle commented in a recent commit that there are "magic numbers". These happen when we have a number which does something special, but we have no documentation about what that special behavior is. In your case, it would be worth creating a variable called `final String COLOR_GOLD = "#b1810b"`. That variable name becomes the documentation. At that point, is it worth adding another comment to say what that variable does? Probably not; I understand what it does just by looking at the variable name. Additional comments would just clutter the source code.

You've also got a few comments in there that say things like "Normal onCreate method calls". If they're normal, then there's no need to put a comment on them. Comments should document behavior which you think might be hard for your co-programmers to understand, not all behavior.

Ironically, a perfect codebase would be one with no comments because the code in it is so well-named and clear that I don't need comments to understand what it does. But perfection rarely happens in practice; the reality is always somewhere in the middle.
